### ISSUE TITLE
error: unable to create file src/aux.js: No such file or directory

### ISSUE THREAD

**Issue by kfern** [DaveHub5/prueba-reference#1]
> $ git clone https://github.com/DaveHub5/prueba-reference.git

Cloning into 'prueba-reference'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 41 (delta 12), reused 35 (delta 8), pack-reused 0
Unpacking objects: 100% (41/41), done.
error: unable to create file src/aux.js: No such file or directory
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by DaveHub5** [comment]
git clone https://github.com/DaveHub5/prueba-reference
Cloning into 'prueba-reference'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 45 (delta 15), reused 40 (delta 12), pack-reused 0
Unpacking objects: 100% (45/45), done.

**Comment by kfern** [comment]
@DaveHub5: Gracias por responder tan rápido :-)

Lo he vuelto a probar y me da el mismo error. La única diferencia es el número de archivos

$ git clone https://github.com/DaveHub5/prueba-reference.git
Cloning into 'prueba-reference'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 45 (delta 15), reused 40 (delta 12), pack-reused 0
Unpacking objects: 100% (45/45), done.
error: unable to create file src/aux.js: No such file or directory
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Parece que el problema está relacionado con la rama master

> $ cd prueba-reference/
> $ git checkout master

error: The following untracked working tree files would be overwritten by checkout:
        .gitignore
        README.md
        db.json
        package.json
        public/favicon.ico
        public/index.html
        public/manifest.json
        src/App.css
        src/App.js
        src/App.test.js
        src/formp.js
        src/index.css
        src/index.js
        src/logo.svg
        src/prueba.js
        src/serviceWorker.js
        yarn.lock
Please move or remove them before you switch branches.
Aborting

¿Alguna idea? Es la primera vez que me encuentro con este problema

Mi versión de git es "git version 2.19.1.windows.1" y el sistema operativo Windows 7

**Comment by DaveHub5** [comment]
Estoy utilizando la version de escritorio de GitHub 1.6.0 para Mac y descargandolo del modo
    git clone https://github.com/DaveHub5/prueba-reference.git
    cd prueba-reference
    npm install
    npm start

**Comment by kfern** [comment]
Parece que las versiones de git no se llevan bien.

¿Qué te aparece al ejecutar los siguientes comandos?

$ cd prueba-reference/
$ git checkout -b master
$ git checkout master

**Comment by DaveHub5** [comment]
git checkout -b master
fatal: A branch named 'master' already exists.
git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.

**Comment by kfern** [comment]
El problema está con el archivo src/aux.js. ¿Puede ser que no hayas subido los cambios después de borrar el archivo?

Sin tocar nada esto me aparece cuando ejecuto git status
>$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    src/aux.js

>$ git checkout -f HEAD
error: unable to create file src/aux.js: No such file or directory
Your branch is up to date with 'origin/master'.

**Comment by DaveHub5** [comment]
Lo he subido varias veces, no se que puede pasar

**Comment by DaveHub5** [comment]
git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Comment by kfern** [comment]
Lo único que parece claro es que cuando me descargo el repositorio hay cambios que no están actualizados en la rama master

![image](https://user-images.githubusercontent.com/1898891/51697182-81706f00-2007-11e9-929c-a710ec2bbfae.png)

¿Has importado en github un repositorio git que ya tenías?

**Comment by kfern** [comment]
¿Has ejecutado git push?

**Comment by kfern** [comment]
Quizás lo más limpio sea crear de nuevo la rama master o probar a borrar el archivo, subir los cambios, volver a ponerlo y subir los cambios de nuevo.

¿Se te ocurre alguna otra idea?

**Comment by DaveHub5** [comment]
He tratado de crear otro repositorio pero al ejecutar
git remote add origin https://github.com/DaveHub5/newPruebaReference.git
fatal: remote origin already exists.

**Comment by DaveHub5** [comment]
¿Puedes probar con el nuevo repositorio?, trate de realizarlo de la forma mas limpia posible

**Comment by kfern** [comment]
@DaveHub5 

Ya debería estar resuelto. ¿Puedes hacer un git clone para comprobarlo? También deberías comprobar si falta algún archivo.

Los pasos que he seguido han sido los siguientes:
git clone
git commit
git push
Esta operación eliminó todos los archivos del repositorio
git add
git commit
git push
Ha dejado el repositorio en su estado actual. Ahora al ejecutar git clone el repositorio se descarga correctamente.

Dejo abierta la incidencia hasta que confirmes que puedes clonar el repositorio

**Comment by kfern** [comment]
@DaveHub5 :+1: El repositorio https://github.com/DaveHub5/prueba-ref si se puede clonar sin problemas

**Comment by DaveHub5** [comment]
¿Trabajamos en ese a partir de ahora entonces?

**Comment by kfern** [comment]
¿Has probado a clonarte este?

**Comment by DaveHub5** [comment]
Si, se clona sin problemas, ¿cambio algun archivo y lo subo?

**Comment by kfern** [comment]
Ok. Podemos usar este repositorio. Puedes borrar los otros. Cierro esta incidencia
