### ISSUE TITLE
Uncaught TypeError: _this.props.save is not a function

### ISSUE THREAD

**Issue by kfern** [DaveHub5/prueba-reference#11]
@DaveHub5 

En la rama develop, al pulsar en el botón Save aparece el error "**Uncaught TypeError: _this.props.save is not a function**" en la consola.

![image](https://user-images.githubusercontent.com/1898891/52799547-52837100-307a-11e9-8790-fa4a7adeb29e.png)

**Comment by DaveHub5** [comment]
Olvide por completo la funcionalidad del boton, ¿debe de existir el botón o solo los formularios?, ¿en caso de existir cuál seria su funcionalidad?

**Comment by kfern** [comment]
Un botón Guardar sólo debe existir en Crear y Editar. En Listar o Borrar no tiene mucho sentido.
