### ISSUE TITLE
Datos en el dataProvider

### ISSUE THREAD

**Issue by kfern** [DaveHub5/prueba-reference#15]
@DaveHub5 
Deberías rehacer los datos que gestiona el dataProvider para que se incluyan solo los campos que se estén usando. Además cada registro debería ser completamente diferente de cualquier otro. Ahora mismo todos los registros tienen los mismos valores en varios campos.

**Comment by DaveHub5** [comment]
No entiendo del todo a que se refiere, en "Deberías rehacer los datos que gestiona el dataProvider para que se incluyan solo los campos que se estén usando.", ¿se refiere a que en el "create" por ejemplo solo aparezca la fecha?
En cuanto al otro apartado, ¿existe alguna forma de crear un número tan grande de registros de otra forma que no sea la manual con un editor de texto añadiendo registro a registro?

**Comment by kfern** [comment]
@DaveHub5 

Me refiero a los datos que están en el archivo db.json. Hay información que no se usa y otra que debería estar, como por ejemplo campos fecha.

La creación de registros para las pruebas puedes hacerlas de muchas formas. Desde crearte tu propia función a usar servicios online. Puedes mirar https://danibram.github.io/mocker-data-generator/, https://stackoverflow.com/questions/53755057/generate-millions-of-mock-data-using-nodejs o buscar en Google si las anteriores no te sirven.

**Comment by DaveHub5** [comment]
Unicamente deje los campos "id" y "date", los necesarios para probar el componente. 
Tengo dos tipos de registros, uno "posts" y otro "comments", en ambos casos se muestra lo mismo pero si me da el visto bueno con el componente, el siguiente paso sería incorporar la función de fecha y hora en vez la de solo fecha, asi como mostrar en "List" la fecha con un formato correcto, no en milisegundos

**Comment by kfern** [comment]
@DaveHub5 

Ya he visto que en el archivo db.json sólo están los campos id y date. A medida que vayas necesitando campos nuevos en las pantallas tendrás que añadirlos previamente en db.json
