### ISSUE TITLE
Module not found: Can't resolve './aux' in 'prueba-reference\src'

### ISSUE THREAD

**Issue by kfern** [DaveHub5/prueba-reference#2]
Al ejecutar npm start se produce un fallo de compilación:

> $ npm start

Starting the development server...

Failed to compile.

./src/App.js
Module not found: Can't resolve './aux' in 'prueba-reference\src'

Puede estar relacionado con #1

**Comment by DaveHub5** [comment]
Cree un branch llamado "aux" que creo ha solucionado el problema

**Comment by DaveHub5** [comment]
Pero el problema que me surge es que si selecciono un post y uno de sus comentarios, si, posteriormente cambio el post, el campo de los comentarios sigue teniendo el anterior, el cual no es valido. 
Sabiendo que se tiene que actualizar el ReferenceInput de los comentarios en el momento que cambie el ReferenceInput de los posts, lo cual se haria llamando a 'onChange' en el primer ReferenceInput, ¿como hago un clear del valor actual del campo de los comentarios?

**Comment by kfern** [comment]
@DaveHub5 

Cuando he intentado actualizarme el repositorio me aparece el siguiente error:

>$ git pull

error: cannot lock ref 'refs/remotes/origin/aux': Unable to create 'prueba-reference/.git/refs/remotes/origin/aux.lock': No such file or directory
From https://github.com/DaveHub5/prueba-reference
 ! [new branch]      aux        -> origin/aux  (unable to update local ref)

Por si acaso, he empezado desde el principio: 

He borrado la carpeta prueba-reference y he ejecutado git clone 
 
>$ git clone https://github.com/DaveHub5/prueba-reference.git

Cloning into 'prueba-reference'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 69 (delta 29), reused 53 (delta 15), pack-reused 0
Unpacking objects: 100% (69/69), done.

>$ cd prueba-reference/

>$ git branch -a

* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/aux
  remotes/origin/master

>$ git checkout master

Already on 'master'
M       src/App.js
M       src/prueba.js
Your branch is up to date with 'origin/master'.

>$ git status

On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)
        modified:   src/App.js
        modified:   src/prueba.js

>$ git checkout aux

fatal: cannot lock ref 'refs/heads/aux': Unable to create 'prueba-reference/.git/refs/heads/aux.lock': No such file or directory

Creo que deberías tomarte el tiempo necesario para entender cómo funciona git y conseguir que lo básico funcione correctamente.

**Comment by kfern** [comment]
@DaveHub5 

Con respecto a https://github.com/DaveHub5/prueba-reference/issues/2#issuecomment-459065139, deberías abrir un nuevo Issue ya que lo que comentas no está relacionado con el asunto

**Comment by DaveHub5** [comment]
He creado una nueva rama a partir de master, llamada develop, estoy probando con diferentes sistemas operativos e incluso con la aplicacion de escritorio GitHub Desktop.

**Comment by kfern** [comment]
Ya he conseguido ejecutarlo, aunque con warnings. He abierto un nuevo issue #5
