### ISSUE TITLE
¿Cómo se ejecuta el dataProvider?

### ISSUE THREAD

**Issue by kfern** [DaveHub5/prueba-reference#3]
@DaveHub5 

En la línea https://github.com/DaveHub5/prueba-reference/blob/5df008330bc8bb348fd009e420452dd1dd8f57fc/src/App.js#L8 se usa un servicio local en el puerto 3001.

¿Qué tendría que hacer para tener el data provider funcionando?

**Comment by DaveHub5** [comment]
En una carpeta nueva añades el archivo db.json que acabo de añadir al directorio raiz,
en esa carpeta ejecutas 
`npm install -g json-server`
y lo ejecutas del modo
`json-server --watch db.json --port 3001`
por defecto se inicializa en el puerto 3000, pero como este esta ocupado por React-Admin lo ejecuto en el 3001

**Comment by kfern** [comment]
@DaveHub5 Gracias. He creado un PR #6 para que sea algo más sencillo de recordar
