### ISSUE TITLE
Clear del Campo Comentarios

### ISSUE THREAD

**Issue by DaveHub5** [DaveHub5/prueba-reference#4]
Si se selecciona un post y uno de sus comentarios, y, posteriormente se cambia el post, el campo de los comentarios sigue teniendo el anterior, el cual no es valido.
Sabiendo que se tiene que actualizar el ReferenceInput de los comentarios en el momento que cambie el ReferenceInput de los posts, lo cual se haria llamando a 'onChange' en el primer ReferenceInput, ¿cómo hago un clear del valor actual del campo de los comentarios? o en su defecto, ¿cómo obtengo una referencia del segundo ReferenceInput?

**Comment by kfern** [comment]
¿Es el mismo caso de https://marmelab.com/react-admin/Inputs.html#linking-two-inputs?

**Comment by DaveHub5** [comment]
No exactamente, porque en él se invoca la función de redux dentro del FormData, concretamente en el onChange del segundo ReferenceInput, y lo que yo quiero hacer es invocarla en el onChange del primer ReferenceInput y, no dispongo de la funcion dispatch que te provee el FormData al hacerlo fuera de este.

**Comment by kfern** [comment]
¿Se te ocurren soluciones alternativas?

**Comment by DaveHub5** [comment]
He probado varias cosas pero ninguna funciono, la que mas viable veia era crear una clase y controlar la variable desde el 'state' de esta, pero no consigo tomar el valor que obtiene el segundo ReferenceInput cuando seleccionas alguna opcion.

**Comment by kfern** [comment]
Hola. ¿Has conseguido tener funcionando el ejemplo que viene en la documentación de dos campos enlazados? El caso que tenemos que resolver es muy parecido

**Comment by DaveHub5** [comment]
Siguiendo tu consejo consegui solucionar el problema del refresh, ahora trato de solucionar el problema de que aparezcan el numero tan grande de registros.
Cierro
