### ISSUE TITLE
develop: npm start: Compiled with warnings

### ISSUE THREAD

**Issue by kfern** [DaveHub5/prueba-reference#5]
>$ git checkout develop

Switched to a new branch 'develop'
Branch 'develop' set up to track remote branch 'develop' from 'origin'.

>$ npm start

> prueba-reference@0.1.0 start david\prueba-reference
> react-scripts start

Starting the development server...

Compiled with warnings.

./src/prueba.js
  Line 2:  'List' is defined but never used                 no-unused-vars
  Line 2:  'SelectInput' is defined but never used          no-unused-vars
  Line 3:   'Datagrid' is defined but never used             no-unused-vars
  Line 3:  'TextField' is defined but never used            no-unused-vars
  Line 3:  'ReferenceField' is defined but never used       no-unused-vars
  Line 3:  'EditButton' is defined but never used           no-unused-vars
  Line 4:  'required' is defined but never used             no-unused-vars
  Line 5:   'ReferenceArrayInput' is defined but never used  no-unused-vars
  Line 5:  'SelectArrayInput' is defined but never used     no-unused-vars
  Line 5:  'Show' is defined but never used                 no-unused-vars

**Comment by DaveHub5** [comment]
Ya resubi la nueva version sin warnings
