### ISSUE TITLE
Usar datos más sencillos de entender

### ISSUE THREAD

**Issue by kfern** [DaveHub5/prueba-reference#7]
@DaveHub5 Los datos que se están usando no ayudan a entender el ejemplo. En los desplegables no deberían mostrarse los id de los registros sino información que sea relevante para el usuario. Además, sería conveniente que ambas colecciones tuvieran más de 100 registros cada una, y al menos un post debería tener más de 50 comentarios.

**Comment by DaveHub5** [comment]
Utilice los id para entenderme a la hora de hacer pruebas, pero entiendo que tambien lo tiene que entender usted, asi que cambie los id por el campo titulo.
Cree 100 posts y 50 comentarios para los 12 primeros (para que sirvan como prueba).
Subi la nueva version con estos cambios, incluido el nuevo archivo db.json
