### ISSUE TITLE
Filtro Comentarios

### ISSUE THREAD

**Issue by DaveHub5** [DaveHub5/prueba-reference#8]
El problema que me surge es que en el nuevo Resource 'Prueba2' ya hace un clear cuando se cambia de post y, cambia de comentarios correctamente cuando se cambia de post.
Pero si se selecciona un post y luego un comentario de este, cuando posteriormente se cambia de post siguen apareciendo los comentarios del anterior post, aunque esto solo ocurre cuando seleccionas un comentario, si cambias de post solamente no.
He intentado depurarlo mediante redux-dev-tools pero no he conseguido localizar porque se produce

**Comment by kfern** [comment]
@DaveHub5 ¿Has mirado cuando y cómo se cargan los datos que aparecen en despegable de los comentarios? ¿Sabrías cómo localizar la acción en redux-dev-tools?

**Comment by DaveHub5** [comment]
He observado que la funcion Get_Matching_Acummulate no se produce cuando cambio de posts habiendo seleccionado un comentario, pero no consigo entender porque, no es que se cambien los parámetros de esta, es que directamente no se llama
Función Get_Matching_Acummulate:
`"{"resource":"comments","relatedTo":"undefined@postId","pagination":{"page":1,"perPage":25},"sort":{"field":"id","order":"ASC"},"filter":{"postId":10}}"`

**Comment by kfern** [comment]
Por eso te comentaba que miraras "cuando y cómo" se cargan los datos en el desplegable. 

¿Puedes provocar que se actualicen los datos del segundo desplegable cuando se produce un cambio en el primero? 

Una fuente de información sobre cómo funciona un componente, además de la documentación, es el código fuente.

**Comment by DaveHub5** [comment]
He observado que en las propiedades del elemento 'ReferenceInput' esta 'crudGetMatching', estoy profundizando en redux-form para tratar de interpretarlo, por ahora no lo veo muy claro la verdad.
