### ISSUE TITLE
Incluir en el campo body de comments una referencia al postId y al id del comentario

### ISSUE THREAD

**Issue by kfern** [DaveHub5/prueba-reference#9]
@DaveHub5 

Con los datos actuales no es fácil de determinar si los comentarios que se están mostrando son los correctos ya que en todos se muestra el mismo texto en el campo body.

El campo body ahora mismo tiene el texto "asome comment" en todos los casos: 
  "comments": [
    { "postId": 1, "id": 1, "body": "asome comment" },

Sería más fácil de entender el ejemplo si fuera:
  "comments": [
    { "postId": 1, "id": 1, "body": "asome comment id 1 postId 1" },
	
¿Puedes cambiar los datos de prueba?

**Comment by DaveHub5** [comment]
Hecho
